services:  
  markethub-ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: markethub-ui
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - "8000:8000"
    volumes:
      - ./ui:/app
      - /app/node_modules

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    env_file:
      - ./.env
    depends_on:
      markethub-db:
        condition: service_healthy
    ports:
      - "8001:8000"

  catalog-service:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    container_name: catalog-service
    env_file:
      - ./catalog-service/catalog.env
    depends_on:
      markethub-db:
        condition: service_healthy
    ports:
      - "8002:8000"

  commerce-service:
    build:
      context: ./commerce-service
      dockerfile: Dockerfile
    container_name: commerce-service
    env_file:
      - ./commerce-service/commerce.env
    depends_on:
      markethub-db:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started
    ports:
      - "8003:8000"

  redis:
    image: redis:7-alpine
    container_name: markethub-redis
    ports:
      - "6379:6379"

  kafka:
    image: apache/kafka:3.7.1
    container_name: markethub-kafka
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    ports:
      - "9092:9092"

  markethub-db:
    image: mysql:8.0
    container_name: markethub-db
    hostname: markethub-db
    env_file:
      - ./.env
      # - ./auth-service/auth.env
      # - ./payment-service/payment.env
      - ./catalog-service/catalog.env
      # - ./commerce-service/commerce.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db/volume:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
